name: Build & Deploy Spring Boot App to AWS EC2

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/mini-football-app:latest

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo ">>> Stopping and removing old container if exists"
            docker rm -f mini-football-app || true
            docker rmi ${{ secrets.DOCKER_USER }}/mini-football-app:latest || true

            echo ">>> Pulling latest image from Docker Hub"
            docker pull ${{ secrets.DOCKER_USER }}/mini-football-app:latest

            echo ">>> Running container"
            docker run -d \
              --name mini-football-app \
              --restart unless-stopped \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=pro \
              -e DB_URL='${{ secrets.DB_URL }}' \
              -e DB_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e JAVA_OPTS="-Xms512m -Xmx512m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0" \
              -e TZ=UTC \
              ${{ secrets.DOCKER_USER }}/mini-football-app:latest

            echo ">>> Status & logs"
            docker ps -a --filter "name=mini-football-app"
